POST /api/Users/ HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json
Content-Length: 251
Origin: http://localhost:3000
Connection: keep-alive
Referer: http://localhost:3000/
Cookie: _ga=GA1.1.1514541091.1609947200; language=de_DE; welcomebanner_status=dismiss; continueCode=3qmmjvZY2r4D17ly3VPXeqxQkGMbhYZH7y0aL5KgpRBow9b8zOW6JnEMNPW2
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin

{
    "role":"admin",
    "email": "erer22@ongoingmedia.de",
    "password": "test1234",
    "passwordRepeat": "test1234",
    "securityQuestion": {
        "id": 11,
        "question": "Dein Lieblingsbuch?",
        "createdAt": "2022-01-26T11:46:49.519Z",
        "updatedAt": "2022-01-26T11:46:49.519Z"
    },
    "securityAnswer": "Tipps vom Hundeflüsterer"
}