# Token holen
token=`curl -s --request POST "http://localhost:8080/auth/realms/master/protocol/openid-connect/token" \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=admin-cli' \
--data-urlencode 'username='$KEYCLOAK_USER \
--data-urlencode 'password='$KEYCLOAK_PASSWORD \
--data-urlencode 'grant_type=password' | jq -r .access_token`